Copy temporary script to /tmp in the VM
because it happened in CI that the local tmp path was
something like: `/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/`
which was not writable (or existent) inside the VM.

`/tmp` should normally exist and be writable in our kairos VMs

```
error: <*errors.withMessage | 0xc0000a61e0>{
    cause: <*errors.errorString | 0xc0000664e0>{
        s: "scp: /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/tmpcmd3258772593: No such file or directory\n",
    },
    msg: "copying the tmp file into the VM",
},
```

Signed-off-by: Dimitris Karakasilis <dimitris@karakasilis.me>